/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package message.queue;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.AmazonSQSException;
import com.amazonaws.services.sqs.model.CreateQueueRequest;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
